app/routes/index.py
import logging

from flask import Blueprint, render_template
from flask_login import current_user

index = Blueprint('index', __name__)
logger = logging.getLogger(__name__)

@index.route('/')
def home_page():
    logger.info('home_page endpoint')
    if current_user.is_authenticated:
        return render_template('index/index_auth.html')
    return render_template('index/index_unauth.html')

app/routes/user.py
import logging
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_user, logout_user, login_required
from ..models.users import User
from ..extensions import bcrypt, db
from ..forms import RegistrationForm, LoginForm


user = Blueprint('user', __name__, url_prefix='/user')
logger = logging.getLogger(__name__)


@user.route('/register', methods=['GET', 'POST'])
def register():
    logger.info('Register endpoint')
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password=hashed_password)
        try:
            db.session.add(user)
            db.session.commit()
            logger.info(f'User registered successfully {form.username.data}')
            return redirect('/user/login')
        except Exception as e:
            logger.error(f'User add error result: {e}')
            db.session.rollback()
            # flash(f'Ошибка при регистрации', 'danger')
    return render_template('/user/register.html', form=form)


@user.route('/login', methods=['GET', 'POST'])
def login():
    logger.info('Login endpoint')
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            logger.info(f'User logged in successfully {form.username.data}')
            return redirect(next_page) if next_page else redirect(url_for('movie.movie_list'))
        else:
            logger.info(f'User login failed {form.username.data}')
            return 'Некорректный никнейм/пароль'

    return render_template('/user/login.html', form=form)


@login_required
@user.route('/profile')
def profile():
    logger.info('Profile endpoint')
    return render_template('/user/profile.html')


@user.route('/logout')
def logout():
    logger.info('Logout endpoint')
    logout_user()
    return redirect('/index')

app/templates/main/_header.html
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="{{ url_for('index.home_page') }}"
       class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <img class="header_img" src="{{ url_for('static', filename='img/logo.jpg') }}" alt="Лого">
    </a>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
{#        <li><a href="{{ url_for('index.home_page') }}" class="nav-link px-2 text-secondary">Главная стрница</a></li>#}
        {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('movie.movie_list') }}" class="nav-link px-2 text-white m-lg-2">Фильмы</a></li>
        {% endif %}
    </ul>

    <div class="text-end d-flex align-items-center">
        {% if current_user.is_authenticated %}
            <button type="button" class="btn btn-outline-light m-2" data-bs-toggle="modal" data-bs-target="#modal">Поиск
                фильмов...
            </button>
            <div class="dropdown">
                <button class="btn btn-outline-light dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    Меню
{#                    <img src="{{ current_user.avatar }}" alt="Аватар" class="rounded-circle"#}
{#                         style="width: 40px; height: 40px;">#}
                </button>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                    <li><a class="dropdown-item" href="{{ url_for('user.profile') }}">Профиль</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('user.logout') }}">Выйти</a></li>
                </ul>
            </div>

            {#            <a href="{{ url_for('user.logout') }}" type="button" class="btn btn-outline-light me-2">Выйти</a>#}
        {% else %}
            <a href="{{ url_for('user.login') }}" type="button" class="btn btn-outline-light me-2">Войти</a>
            <a href="{{ url_for('user.register') }}" type="button" class="btn btn-outline-light">Регистрация</a>
        {% endif %}
    </div>
</div>

app/templates/main/_search_window.html
<div id="modal" class="modal fade" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Поиск фильмов</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
                <form id="movieSearchForm">
                    <div class="mb-3">
                        <label for="movieSearchInput" class="form-label">Введите название фильма</label>
                        <input type="text" id="movieSearchInput" class="form-control" placeholder="Например: Интерстеллар">
                    </div>
                    <button type="submit" class="btn btn-primary">Искать</button>
                </form>
                <ul id="movieSearchResult" class="list-group m-3"></ul>
            </div>
        </div>
    </div>
</div>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bs/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/movie_list.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body data-bs-theme="dark">
    <div class="page">
        {% if not request.endpoint in ('user.login', 'user.register') %}
        	<header class="header">{% include 'main/_header.html' %}</header>
            {% include 'main/_search_window.html' %}
        {% endif %}
        <main class="content">{% block content %}{% endblock %}</main>
        <footer class="footer">{% include 'main/_footer.html' %}</footer>
    </div>
{#    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>#}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/search_window.js') }}"></script>
    <script src="{{ url_for('static', filename='js/change_status.js') }}"></script>
</body>
</html>