app/routes/movies.py
import logging

from flask import Blueprint, render_template, request, jsonify, redirect, url_for
from flask_login import current_user
from ..models.posts import Post, search_movie, DetailMovie, Genre, Actor, status_id_to_str
from ..extensions import db


movie = Blueprint('movie', __name__, url_prefix='/movie')
logger = logging.getLogger(__name__)


@movie.before_request
def require_login():
    if not current_user.is_authenticated:
        logger.debug('User not logged in, redirecting to login')
        return redirect(url_for('user.login'))


@movie.route('/', methods=['GET'])
def movie_list():
    logger.info('Movie list endpoint')
    title = request.args.get('title', None)
    year = request.args.get('year', None)
    status = request.args.get('status', None)
    logger.debug(f'Movie_list setup args: {title=} {status=} {year=}')

    movies_query = Post.query.filter_by(post_author=current_user.id)

    if title:
        title = str(title).title()
        movies_query = movies_query.filter(Post.title.like(f"%{title}%"))
    if year:
        movies_query = movies_query.filter(Post.year == year)
    if status:
        movies_query = movies_query.filter(Post.status == status)

    movies_query = movies_query.order_by(Post.post_creation_date.desc()).all()

    filters = []
    if status:
        status = status_id_to_str(status)
        filters.append({'key': 'status', 'value': status, 'label': f'Статус: {status}'})
    if year:
        filters.append({'key': 'year', 'value': year, 'label': f'Год: {year}'})
    if title:
        filters.append({'key': 'title', 'value': title, 'label': f'Название: {title}'})

    logger.debug(f'Movie_list filters result: {filters}')

    current_args = request.args.to_dict()

    logger.debug(f'Movie_list current args: {current_args}')

    return render_template('movies/movies_list.html', movies=movies_query, filters=filters, current_args=current_args)


@movie.app_template_filter('dict_without')
def dict_without(d, key):
    logger.debug(f'Movie_list filter: {d}')
    if key in d:
        d = d.copy()
        d.pop(key)
        logger.debug(f'Movie_list filter result: {d}')
    return '&'.join([f'{k}={v}' for k, v in d.items()])


@movie.route('/add', methods=['POST'])
def add_movie():
    logger.info('Add_movie endpoint')
    movie_api_id = request.args.get('movie_id')
    logger.debug(f'Movie_api_id: {movie_api_id}')

    if not movie_api_id:
        logger.error('Movie id not provided, redirecting to add_movie')
        return jsonify({'message': 'ID фильма не передан!'}), 400

    result = search_movie(movie_id=movie_api_id)
    logger.debug(f'Movie_api_id: {movie_api_id} result: {result}')

    if not result:
        logger.error('Movie not found in api database, redirecting to add_movie')
        return jsonify({'message': 'Фильм не найден!'}), 404

    try:
        title = result.get('name')
        post_author = current_user.id
        description = result.get('description')
        year = result.get('year')
        movie_type = result.get('type')
        poster = result.get('poster', {}).get('url', 'static/img/logo.jpg')
        rating = result.get('rating').get('imdb')

        genre = result.get('genres', [])
        genre_names = [genre.get('name') for genre in genre]
        logger.debug(f'Movie_api_id: {movie_api_id} result: {genre_names}')

        persons = result.get('persons', [])
        top_actors = persons[:5]
        actors_data = [(actor.get('id'), actor.get('name'), actor.get('photo')) for actor in top_actors]
        logger.debug(f'Movie_api_id: {movie_api_id} actors: {actors_data}')

        new_movie = Post(
            movie_api_id=movie_api_id,
            post_author=post_author,
            title=title,
            description=description,
            year=year,
            type=movie_type,
            poster=poster,
            status=1,
            rating=rating
        )

        db.session.add(new_movie)
        db.session.flush()

        for genre_name in genre_names:
            existing_genre = Genre.query.filter_by(name=genre_name).first()
            if not existing_genre:
                existing_genre = Genre(name=genre_name)
                db.session.add(existing_genre)
                logger.debug(f'{genre_name=} added to db')
            new_movie.genres.append(existing_genre)


        for actor_api_id, name, photo in actors_data:
            existing_actor = Actor.query.filter_by(actor_api_id=actor_api_id).first()
            if not existing_actor:
                existing_actor = Actor(actor_api_id=actor_api_id, name=name, photo=photo)
                db.session.add(existing_actor)
                logger.debug(f'{actor_api_id=}, {name=}, {photo=} added to db')
            new_movie.actors.append(existing_actor)

        db.session.commit()
        logger.info(f'Movie added succesfully: {movie_api_id}')
        return jsonify({"message": "Фильм успешно добавлен!"}), 200
    except Exception as e:
        db.session.rollback()
        logger.error(f'Movie add error result: {e}')
        return jsonify({"message": "Ошибка при добавлении фильма!"}), 500


@movie.route('/<int:api_id>')
def movie_detail(api_id):
    logger.info('Movie detail endpoint')
    post = Post.query.filter_by(movie_api_id=api_id).first()
    if not post:
        logger.error(f'Movie bot found in db by {api_id=}')
        return jsonify({'message': 'Фильм не найден!'}), 404

    genres = [genre.name for genre in post.genres]
    actors = post.actors
    movie = DetailMovie(post=post, actors=actors, genres=genres)
    actors_info = list(zip(movie.actor_name, movie.actor_photo))
    logger.info(f'Movie detail result: {movie}')
    return render_template('movies/movie_detail.html', movie=movie, actors_info=actors_info)


@movie.route('/search', methods=['GET'])
def movie_search():
    logger.info('Movie search endpoint')
    title = request.args.get('title')
    if not title:
        logger.error(f'Movie title not provided {title=}, redirecting to add_movie')
        return jsonify({'error': 'Title is required'}), 400

    movies = search_movie(movie_title=title)
    if not movies:
        logger.error(f'Movie not found in api db: {title}')
        return jsonify({'error': 'No movies found'})

    movie_results = []
    for movie in movies:
        is_added = Post.query.filter_by(movie_api_id=movie.get('id'), post_author=current_user.id).first()
        movie['is_added'] = True if is_added else False
        movie_results.append(movie)

    logger.debug(f'Search result {movie_results=}')
    return jsonify(movie_results), 200


@movie.route('/change_status', methods=['POST'])
def change_status():
    logger.info('Movie change endpoint')
    data = request.get_json()
    movie_id = data.get('movie_id')
    status = data.get('status')

    movie = Post.query.filter_by(id=movie_id, post_author=current_user.id).first()
    if not movie:
        logger.error(f'Movie not found in api db: {movie_id=}')
        return jsonify({'success': False, 'message': 'Фильм не найден'}), 404

    try:
        movie.status = status
        db.session.commit()
        logger.info(f'Movie status changed to {status}')
        return jsonify({'success': True}), 200
    except Exception as e:
        logger.error(f'Movie status change failed: {e}')
        db.session.rollback()
        return jsonify({'success': False, 'message': str(e)}), 500

app/templates/movies/_rating_block.html
{% set rating = movie.rating %}
{% set red = (10 - rating) * 25.5 %}
{% set green = (rating - 1) * 25.5 %}
{% set gradient_color = 'rgb(' ~ red | round ~ ',' ~ green | round ~ ', 0)' %}

<div class="rating-block"
     style="background: {{ gradient_color }}; padding: 10px; border-radius: 5px;">
    <p class="card-text mb-0" style="color: white; font-size: 0.8em;">
        Imdb: {{ rating }}</p>
</div>

app/templates/movies/_status_block.html
<div class="dropdown">
    <button
            class="btn dropdown-toggle {% if movie.status == 1 %}btn-secondary{% elif movie.status == 2 %}btn-danger{% elif movie.status == 3 %}btn-warning{% elif movie.status == 4 %}btn-success{% endif %}"
            type="button"
            id="dropdownMenuButton-{{ movie.id }}"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            style="font-size: 0.8rem; padding: 10px 20px;">
        {% if movie.status == 1 %}
            Посмотреть позже
        {% elif movie.status == 2 %}
            Не досмотрел
        {% elif movie.status == 3 %}
            На один раз
        {% elif movie.status == 4 %}
            Восторг
        {% endif %}
    </button>
    <ul class="dropdown-menu"
        aria-labelledby="dropdownMenuButton-{{ movie.id }}">
        <li><a class="dropdown-item" href="#"
               onclick="changeStatus({{ movie.id }}, 1)">Посмотреть позже</a></li>
        <li><a class="dropdown-item" href="#"
               onclick="changeStatus({{ movie.id }}, 2)">Не досмотрел</a></li>
        <li><a class="dropdown-item" href="#"
               onclick="changeStatus({{ movie.id }}, 3)">На один раз</a>
        </li>
        <li><a class="dropdown-item" href="#"
               onclick="changeStatus({{ movie.id }}, 4)">Восторг</a></li>
    </ul>
</div>

app/templates/movies/_type_block.html
<div class="rating-block"
     style="background: none; padding: 10px; border-radius: 5px;">
    <p class="card-text mb-0" style="color: white; font-size: 0.8em;">
        {{ movie.type }}</p>
</div>

app/templates/movies/movie_detail.html
{% extends "main/base.html" %}

{% block title %}{{ movie.title }}{% endblock %}

{% block content %}
<div class="mt-4">
            <a href="{{ url_for('movie.movie_list') }}" class="btn btn-dark"><--К списку фильмов</a>
        </div>
    <div class="container py-5">

        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card bg-dark text-white shadow-lg">
                    <div class="row g-0">
                        <div class="col-md-4 flex-column" style="flex-grow: 1;">
                            <img src="{{ movie.poster }}" class="img-fluid rounded-start" alt="{{ movie.title }}"
                                 style="object-fit: cover; height: 100%; width: 100%;">
                        </div>

                        <div class="col-md-8">
                            <div class="card-body"><h2 class="card-title">{{ movie.title }} ({{ movie.year }})</h2>
                                <div class="d-flex justify-content-between align-items-center mt-4">
                                    {% include 'movies/_type_block.html' %}
                                    {% include 'movies/_rating_block.html' %}
                                    {% include 'movies/_status_block.html' %}
                                </div>
                                <p class="card-text mt-3">{{ movie.description or 'Описание фильма отсутствует.' }}</p>

                                <h5>Жанры</h5>
                                <p class="card-text">
                                    {% if movie.genres %}
                                        {{ movie.genres|join(', ') }}
                                    {% else %}
                                        Жанры не указаны.
                                    {% endif %}
                                </p>

                                <h5>Актеры</h5>
                                <div class="row">
                                    {% for name, photo in actors_info %}
                                        <div class="col-md-4 mb-3 d-flex flex-column justify-content-center align-items-center">
                                            <img src="{{ photo }}" class="img-fluid rounded-circle" alt="{{ name }}"
                                                 style="max-width: 50px;">
                                            <p class="mt-2">{{ name }}</p>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/movies/movies_list.html
{% extends 'main/base.html' %}

{% block title %}Фильмы{% endblock %}

{% block content %}
    {% if movies %}
        <div class="album py-5 bg-body-tertiary">
            <div class="container py-3">
                <div class="d-flex flex-row">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <button class="btn btn-outline-light" type="button" data-bs-toggle="collapse"
                                data-bs-target="#filterCollapse" aria-expanded="false" aria-controls="filterCollapse">
                            Фильтры <i class="bi bi-chevron-down"></i>
                        </button>
                    </div>

                    <div class="d-flex flex-wrap ms-3">
                        {% for filter in filters %}
                            <button
                                    type="button"
                                    class="btn btn-outline-light btn-sm me-2 d-flex align-items-center"
                                    style="height: calc(2.25rem + 2px);"
                                    onclick="window.location.href='{{ url_for('movie.movie_list') }}?{{ current_args | dict_without(filter.key) }}'">
                                {{ filter.label }}
                                <span class="ms-2" style="font-size: 1.2rem;">&times;</span>
                            </button>
                        {% endfor %}
                    </div>
                </div>

                <div class="collapse" id="filterCollapse">
                    <div class="card card-body bg-dark text-white mb-3">
                        <form method="GET" action="{{ url_for('movie.movie_list') }}">
                            <div class="row g-3">
                                <div class="col-md-4">
                                    <label for="titleFilter" class="form-label">Название</label>
                                    <input type="text" class="form-control" id="titleFilter" name="title"
                                           placeholder="Введите название">
                                </div>

                                <div class="col-md-4">
                                    <label for="yearFilter" class="form-label">Год</label>
                                    <input type="number" class="form-control" id="yearFilter" name="year"
                                           placeholder="Введите год">
                                </div>

                                <div class="col-md-4">
                                    <label for="statusFilter" class="form-label">Статус</label>
                                    <select class="form-select" id="statusFilter" name="status">
                                        <option value="" selected>Выберите статус</option>
                                        <option value="1">Посмотреть позже</option>
                                        <option value="2">Не досмотрел</option>
                                        <option value="3">На один раз</option>
                                        <option value="4">Восторг</option>
                                    </select>
                                </div>
                            </div>
                            <div class="d-flex justify-content-end mt-3">
                                <button type="submit" class="btn btn-outline-light">Применить</button>
                                <a href="{{ url_for('movie.movie_list') }}" class="btn btn-outline-secondary ms-2">Сбросить</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>


            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for movie in movies %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <a href="{{ url_for('movie.movie_detail', api_id=movie.movie_api_id) }}"
                                   class="img-hover">
                                    <img id="post_img" src="{{ movie.poster }}" alt="Лого" class="img-fluid">
                                </a>
                                <div class="card-body">
                                    <p class="card-header">{{ movie.title }} {{ movie.year }}</p>
                                    <div class="d-flex justify-content-between align-items-center mt-4">
                                        {% include 'movies/_type_block.html' %}
                                        {% include 'movies/_rating_block.html' %}
                                        {% include 'movies/_status_block.html' %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="custom-vh-75 d-flex justify-content-center align-items-center">
            <div class="text-center text-light p-4 rounded shadow">
                <h4>Сейчас в вашем списке ничего нет.</h4>
                <p class="mb-0 mb-3">Добавим что-нибудь?</p>
                <button type="button" class="btn btn-outline-light m-2" data-bs-toggle="modal" data-bs-target="#modal">
                    Поиск фильмов...
                </button>
            </div>
        </div>
    {% endif %}
{% endblock %}